# -*- coding: utf-8 -*-
"""NLP cie-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f2RjdJ2qzoRtiCKx5I5GRVoz3u49BYbh
"""

import nltk
nltk.download('punkt')
nltk.download('stopwords')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

# Sample FAQ dataset
faq_data = {
    "What is your return policy?": "Our return policy lasts 30 days.",
    "How do I track my order?": "You can track your order using the tracking number provided in the confirmation email.",
    "What payment methods do you accept?": "We accept credit cards, debit cards, and PayPal."
}

# Preprocess the questions
stop_words = set(stopwords.words('english'))
def preprocess(text):
    tokens = word_tokenize(text.lower())
    tokens = [word for word in tokens if word.isalnum() and word not in stop_words]
    return tokens

faq_data_processed = {k: preprocess(k) for k in faq_data.keys()}

# Simple chatbot function
def faq_chatbot(question):
    question_tokens = preprocess(question)
    for faq, faq_tokens in faq_data_processed.items():
        if set(question_tokens).intersection(faq_tokens):
            return faq_data[faq]
    return "Sorry, I don't have an answer for that."

# Test the chatbot
print(faq_chatbot("How can I track my order?"))